spring:
  application:
    name: intershop
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  r2dbc:
    url: r2dbc:h2:mem:///shopdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: intershop-client
            client-secret: YVb78tiJaf3xAIbbEHdd4QTNcvgXzTmI
            authorization-grant-type: client_credentials
            scope: payment:read,payment:write
        provider:
          keycloak:
            issuer-uri: http://payment-service:8081/realms/intershop

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    io.r2dbc: INFO
    org.springframework.r2dbc: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    io.github.danjos.intershop: DEBUG

# Payment Service Configuration
payment:
  service:
    url: http://payment-service:8081
    timeout: 5000
